name: Publish to PSGallery

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Publish Script
        shell: pwsh
        env:
          PSGALLERY_KEY: ${{ secrets.PSGALLERY_API }}
        run: |
          Install-Module PowerShellGet -Force -Scope CurrentUser
          Publish-Script -Path "./installVsDevWithPwsh7.ps1" -NuGetApiKey $env:PSGALLERY_KEY